server.port=8082
spring.application.name=servico-usuarios

# Banco H2 - servico de usuarios (banco SEPARADO do servico-livros)
spring.datasource.url=jdbc:h2:file:./data/usuarios-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Console H2 (acesse em http://localhost:8082/h2-console e coloque o link JDBC URL: jdbc:h2:file:./data/usuarios-db)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# URL do servico de livros
livros.service.url=http://localhost:8081
